spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=false

# Deshabilitado por incompatibilidad con Spring Boot 3.2.5 en Render
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
