services:
  - type: web
    name: ms-pacientes
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./ms-pacientes/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pacientes-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: pacientes-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: pacientes-db
          property: password

databases:
  - name: pacientes-db
    databaseName: pacientesdb
    plan: free
    region: oregon
