services:
  - type: web
    name: ms-pacientes
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./ms-pacientes/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: RENDER_DB_HOST
        fromDatabase:
          name: pacientes-db
          property: host
      - key: RENDER_DB_PORT
        fromDatabase:
          name: pacientes-db
          property: port
      - key: RENDER_DB_NAME
        fromDatabase:
          name: pacientes-db
          property: database
      - key: RENDER_DB_USER
        fromDatabase:
          name: pacientes-db
          property: user
      - key: RENDER_DB_PASSWORD
        fromDatabase:
          name: pacientes-db
          property: password

databases:
  - name: pacientes-db
    databaseName: pacientesdb
    plan: free
    region: oregon
