spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=false

spring.datasource.url=jdbc:postgresql://${RENDER_DB_HOST}:${RENDER_DB_PORT}/${RENDER_DB_NAME}
spring.datasource.username=${RENDER_DB_USER}
spring.datasource.password=${RENDER_DB_PASSWORD}

spring.flyway.enabled=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
